export const PUBLIC_SUPPORTED_LOCALES = ["en", "zh-CN", "zh-TW", "vi"] as const;
export type PublicSupportedLocale = typeof PUBLIC_SUPPORTED_LOCALES[number];
export const PUBLIC_ROUTE_COPY_KEYS = ["about", "careers", "privacy", "terms", "refund", "acceptableUse", "pinterest", "welcome", "dataDeletion", "login", "signup"] as const;
export type PublicRouteCopyKey = typeof PUBLIC_ROUTE_COPY_KEYS[number];

export type PublicRouteCopy = {
  eyebrow: string; title: string; body: string; cta: string;
  email: string; password: string; google: string; divider: string; loading: string;
  alternatePrompt: string; alternateCta: string; legalNotice: string; passwordHint: string;
  forgotPassword: string; resetEmailRequired: string; resetSent: string;
  confirmationTitle: string; confirmationBody: string; planPrefix: string;
  signInPrompt: string; signInCta: string; termsLabel: string; privacyLabel: string;
};

type Core = Pick<PublicRouteCopy, "eyebrow" | "title" | "body" | "cta">;
type AuthCopy = Omit<PublicRouteCopy, keyof Core | "signInPrompt" | "signInCta" | "termsLabel" | "privacyLabel">;
const AUTH: Record<PublicSupportedLocale, AuthCopy> = {
  en: { email: "Email", password: "Password", google: "Continue with Google", divider: "or", loading: "Signing in…", alternatePrompt: "Don’t have an account?", alternateCta: "Start free trial", legalNotice: "By signing up you agree to our Terms and Privacy Policy.", passwordHint: "min 8 characters", forgotPassword: "Forgot password?", resetEmailRequired: "Enter your email first.", resetSent: "Check your email for a password reset link.", confirmationTitle: "Check your email", confirmationBody: "We sent a confirmation link to your email. Click it to activate your account and get started.", planPrefix: "Plan:" },
  "zh-CN": { email: "邮箱", password: "密码", google: "使用 Google 继续", divider: "或", loading: "正在登录…", alternatePrompt: "还没有账户？", alternateCta: "免费开始试用", legalNotice: "注册即表示您同意我们的服务条款和隐私政策。", passwordHint: "至少 8 个字符", forgotPassword: "忘记密码？", resetEmailRequired: "请先输入您的邮箱。", resetSent: "请查看邮箱中的密码重置链接。", confirmationTitle: "请查看您的邮箱", confirmationBody: "我们已向您的邮箱发送确认链接。点击链接即可激活账户并开始使用。", planPrefix: "套餐：" },
  "zh-TW": { email: "電子郵件", password: "密碼", google: "使用 Google 繼續", divider: "或", loading: "正在登入…", alternatePrompt: "還沒有帳戶？", alternateCta: "免費開始試用", legalNotice: "註冊即表示您同意我們的服務條款和隱私權政策。", passwordHint: "至少 8 個字元", forgotPassword: "忘記密碼？", resetEmailRequired: "請先輸入您的電子郵件。", resetSent: "請查看電子郵件中的密碼重設連結。", confirmationTitle: "請查看您的電子郵件", confirmationBody: "我們已向您的電子郵件寄送確認連結。點選連結即可啟用帳戶並開始使用。", planPrefix: "方案：" },
  vi: { email: "Email", password: "Mật khẩu", google: "Tiếp tục với Google", divider: "hoặc", loading: "Đang đăng nhập…", alternatePrompt: "Chưa có tài khoản?", alternateCta: "Dùng thử miễn phí", legalNotice: "Khi đăng ký, bạn đồng ý với Điều khoản và Chính sách quyền riêng tư của chúng tôi.", passwordHint: "ít nhất 8 ký tự", forgotPassword: "Quên mật khẩu?", resetEmailRequired: "Hãy nhập email trước.", resetSent: "Hãy kiểm tra email để nhận liên kết đặt lại mật khẩu.", confirmationTitle: "Kiểm tra email của bạn", confirmationBody: "Chúng tôi đã gửi liên kết xác nhận đến email của bạn. Hãy nhấp vào liên kết để kích hoạt tài khoản và bắt đầu.", planPrefix: "Gói:" },
};

const SIGN_IN_EXTRAS: Record<PublicSupportedLocale, Pick<PublicRouteCopy, "signInPrompt" | "signInCta" | "termsLabel" | "privacyLabel">> = {
  en: { signInPrompt: "Already have an account?", signInCta: "Sign in", termsLabel: "Terms", privacyLabel: "Privacy Policy" },
  "zh-CN": { signInPrompt: "已有账户？", signInCta: "登录", termsLabel: "服务条款", privacyLabel: "隐私政策" },
  "zh-TW": { signInPrompt: "已有帳戶？", signInCta: "登入", termsLabel: "服務條款", privacyLabel: "隱私權政策" },
  vi: { signInPrompt: "Đã có tài khoản?", signInCta: "Đăng nhập", termsLabel: "Điều khoản", privacyLabel: "Chính sách quyền riêng tư" },
};

const CORE: Record<PublicSupportedLocale, Record<PublicRouteCopyKey, Core>> = {
  en: {
    about: { eyebrow: "About", title: "Pinterest growth that starts with signals.", body: "VibePin helps creators and businesses turn real Pinterest demand into deliberate content decisions.", cta: "Contact us" }, careers: { eyebrow: "Careers", title: "Help build VibePin.", body: "We are a focused team building Pinterest growth intelligence for creators and businesses.", cta: "Introduce yourself" }, privacy: { eyebrow: "Legal", title: "Privacy Policy", body: "How VibePin collects, uses, protects, and deletes personal and Pinterest-related information.", cta: "Contact support" }, terms: { eyebrow: "Legal", title: "Terms of Service", body: "The terms that govern use of VibePin and its Pinterest-connected features.", cta: "Contact support" }, refund: { eyebrow: "Legal", title: "Refund and Cancellation Policy", body: "Rules for subscription cancellation, eligible refunds, and payment disputes.", cta: "Request a refund" }, acceptableUse: { eyebrow: "Legal", title: "Acceptable Use Policy", body: "Rules for safe, lawful, and responsible use of VibePin and its AI features.", cta: "Report a violation" }, pinterest: { eyebrow: "Pinterest Integration", title: "How VibePin Uses Pinterest", body: "A transparent explanation of our optional Pinterest API and OAuth integration.", cta: "Contact support" }, welcome: { eyebrow: "Subscription confirmed", title: "You’re in.", body: "Your payment went through and your plan is active.", cta: "Start creating" }, dataDeletion: { eyebrow: "Privacy", title: "Data deletion request received", body: "Your deletion request has been received and processed.", cta: "Contact support" }, login: { eyebrow: "Welcome back", title: "Sign in to your account", body: "Use your VibePin account to continue.", cta: "Sign in" }, signup: { eyebrow: "Create your account", title: "Start for free", body: "No credit card is required to get started.", cta: "Create account" },
  },
  "zh-CN": {
    about: { eyebrow: "关于我们", title: "从信号开始的 Pinterest 增长。", body: "VibePin 帮助创作者和企业将真实 Pinterest 需求转化为有计划的内容决策。", cta: "联系我们" }, careers: { eyebrow: "招聘", title: "一起打造 VibePin。", body: "我们是一个专注于为创作者和企业打造 Pinterest 增长情报的小团队。", cta: "自我介绍" }, privacy: { eyebrow: "法律", title: "隐私政策", body: "了解 VibePin 如何收集、使用、保护和删除个人及 Pinterest 相关信息。", cta: "联系支持团队" }, terms: { eyebrow: "法律", title: "服务条款", body: "管理 VibePin 及其 Pinterest 连接功能使用的条款。", cta: "联系支持团队" }, refund: { eyebrow: "法律", title: "退款和取消政策", body: "订阅取消、符合条件的退款和付款争议规则。", cta: "申请退款" }, acceptableUse: { eyebrow: "法律", title: "可接受使用政策", body: "安全、合法且负责任地使用 VibePin 及其 AI 功能的规则。", cta: "举报违规" }, pinterest: { eyebrow: "Pinterest 集成", title: "VibePin 如何使用 Pinterest", body: "对可选 Pinterest API 与 OAuth 集成的透明说明。", cta: "联系支持团队" }, welcome: { eyebrow: "订阅已确认", title: "欢迎加入。", body: "您的付款已完成，套餐现已生效。", cta: "开始创作" }, dataDeletion: { eyebrow: "隐私", title: "已收到数据删除请求", body: "您的删除请求已收到并已处理。", cta: "联系支持团队" }, login: { eyebrow: "欢迎回来", title: "登录您的账户", body: "使用您的 VibePin 账户继续。", cta: "登录" }, signup: { eyebrow: "创建您的账户", title: "免费开始", body: "开始使用无需信用卡。", cta: "创建账户" },
  },
  "zh-TW": {
    about: { eyebrow: "關於我們", title: "從訊號開始的 Pinterest 成長。", body: "VibePin 協助創作者與企業把真實 Pinterest 需求轉成有計畫的內容決策。", cta: "聯絡我們" }, careers: { eyebrow: "招募", title: "一起打造 VibePin。", body: "我們是專注於為創作者與企業打造 Pinterest 成長情報的小團隊。", cta: "自我介紹" }, privacy: { eyebrow: "法律", title: "隱私權政策", body: "了解 VibePin 如何蒐集、使用、保護與刪除個人及 Pinterest 相關資訊。", cta: "聯絡支援團隊" }, terms: { eyebrow: "法律", title: "服務條款", body: "管理 VibePin 與其 Pinterest 連結功能使用的條款。", cta: "聯絡支援團隊" }, refund: { eyebrow: "法律", title: "退款與取消政策", body: "訂閱取消、符合資格的退款和付款爭議規則。", cta: "申請退款" }, acceptableUse: { eyebrow: "法律", title: "可接受使用政策", body: "安全、合法且負責任使用 VibePin 及其 AI 功能的規則。", cta: "檢舉違規" }, pinterest: { eyebrow: "Pinterest 整合", title: "VibePin 如何使用 Pinterest", body: "對可選 Pinterest API 與 OAuth 整合的透明說明。", cta: "聯絡支援團隊" }, welcome: { eyebrow: "訂閱已確認", title: "您已加入。", body: "您的付款已完成，方案現已啟用。", cta: "開始建立內容" }, dataDeletion: { eyebrow: "隱私", title: "已收到資料刪除請求", body: "您的刪除請求已收到並已處理。", cta: "聯絡支援團隊" }, login: { eyebrow: "歡迎回來", title: "登入您的帳戶", body: "使用您的 VibePin 帳戶繼續。", cta: "登入" }, signup: { eyebrow: "建立您的帳戶", title: "免費開始", body: "開始使用不需要信用卡。", cta: "建立帳戶" },
  },
  vi: {
    about: { eyebrow: "Giới thiệu", title: "Tăng trưởng Pinterest bắt đầu từ tín hiệu.", body: "VibePin giúp người sáng tạo và doanh nghiệp biến nhu cầu Pinterest thực thành quyết định nội dung có chủ đích.", cta: "Liên hệ" }, careers: { eyebrow: "Tuyển dụng", title: "Cùng xây dựng VibePin.", body: "Chúng tôi là đội ngũ tập trung xây dựng thông tin tăng trưởng Pinterest cho người sáng tạo và doanh nghiệp.", cta: "Giới thiệu bản thân" }, privacy: { eyebrow: "Pháp lý", title: "Chính sách quyền riêng tư", body: "Cách VibePin thu thập, sử dụng, bảo vệ và xóa thông tin cá nhân và dữ liệu liên quan đến Pinterest.", cta: "Liên hệ hỗ trợ" }, terms: { eyebrow: "Pháp lý", title: "Điều khoản dịch vụ", body: "Các điều khoản chi phối việc sử dụng VibePin và các tính năng kết nối Pinterest.", cta: "Liên hệ hỗ trợ" }, refund: { eyebrow: "Pháp lý", title: "Chính sách hoàn tiền và hủy", body: "Quy tắc hủy đăng ký, hoàn tiền đủ điều kiện và tranh chấp thanh toán.", cta: "Yêu cầu hoàn tiền" }, acceptableUse: { eyebrow: "Pháp lý", title: "Chính sách sử dụng chấp nhận được", body: "Quy tắc sử dụng VibePin và các tính năng AI an toàn, hợp pháp và có trách nhiệm.", cta: "Báo cáo vi phạm" }, pinterest: { eyebrow: "Tích hợp Pinterest", title: "VibePin sử dụng Pinterest như thế nào", body: "Giải thích minh bạch về tích hợp Pinterest API và OAuth tùy chọn của chúng tôi.", cta: "Liên hệ hỗ trợ" }, welcome: { eyebrow: "Đã xác nhận đăng ký", title: "Bạn đã tham gia.", body: "Thanh toán của bạn đã hoàn tất và gói đã hoạt động.", cta: "Bắt đầu tạo" }, dataDeletion: { eyebrow: "Quyền riêng tư", title: "Đã nhận yêu cầu xóa dữ liệu", body: "Yêu cầu xóa dữ liệu của bạn đã được nhận và xử lý.", cta: "Liên hệ hỗ trợ" }, login: { eyebrow: "Chào mừng trở lại", title: "Đăng nhập tài khoản", body: "Dùng tài khoản VibePin để tiếp tục.", cta: "Đăng nhập" }, signup: { eyebrow: "Tạo tài khoản", title: "Bắt đầu miễn phí", body: "Không cần thẻ tín dụng để bắt đầu.", cta: "Tạo tài khoản" },
  },
};

export function getPublicCopy(locale: string, route: PublicRouteCopyKey): PublicRouteCopy {
  const language = (PUBLIC_SUPPORTED_LOCALES as readonly string[]).includes(locale) ? locale as PublicSupportedLocale : "en";
  return { ...AUTH[language], ...SIGN_IN_EXTRAS[language], ...CORE[language][route] };
}
