// Read-only review: instantiate the existing local SQL harness in memory and
// append independent expected-safe adversarial checks. No production edit/I/O.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import Module from "node:module";
import ts from "../../../web/node_modules/typescript";

const probePath = resolve(process.cwd(), "../.superpowers/sdd/2026-09-16-video-pin-p0/task-7-review-probes.ts");
const original = readFileSync(probePath, "utf8");
const prefix = original.slice(0, original.indexOf(" const check=async"));
if (!prefix.endsWith("\n")) throw new Error("Unexpected review harness shape");
const checks = String.raw`
 let failures=0;
 const safe=async(name:string,fn:()=>Promise<void>)=>{
   try{await fn();console.log('PASS '+name);}catch(error){failures++;console.error('FAIL '+name, error instanceof Error ? error.message : error);}
 };
 await safe('concurrent claimed recovery permits only one provider invocation',async()=>{
   const i=makeInput(makeReceipt('r2-concurrent'));
   await deps.confirmPrepare(i);const lease=await deps.leaseMaterialization(i);
   for(const source of await deps.materializeSources(i,lease))await deps.settleItem(i,lease,source);
   await deps.claimReady(i,lease);
   let inspected=0,started=0,dispatched=0;let inspectRelease:any,startRelease:any;
   const inspectGate=new Promise(r=>inspectRelease=r),startGate=new Promise(r=>startRelease=r);
   const racing={...deps,
     inspect:async(input:any)=>{const result=await deps.inspect(input);if(++inspected===2)inspectRelease();await inspectGate;return result;},
     startAttempt:async(input:any,claim:any)=>{const result=await deps.startAttempt(input,claim);console.log('start result',JSON.stringify(result));if(++started===2)startRelease();await startGate;return result;},
     publishVideo:async()=>{dispatched++;return success();}
   };
   const results=await Promise.allSettled([dispatchV76PinterestVideo(i,racing),dispatchV76PinterestVideo(i,racing)]);
   console.log('provider dispatches / results',dispatched,JSON.stringify(results));
   assert.equal(dispatched,1,'one durable attempt must not authorize two sends');
 });
 await safe('next due pass resumes untouched sibling after operational timestamp changed',async()=>{
   const r=makeReceipt('r2-next-run',ds);
   assert.equal((await dispatchV76PinterestVideo(makeInput(r),deps)).outcome,'published');
   currentRevision='2026-09-16T12:00:05.000Z';
   const next=buildDueVideoReceipt({draftId:'r2-next-run',updatedAt:currentRevision,scheduledAt:revision,payload:{contentId:'r2-next-run',title:'Video',media,imageUrl:media[0].url,scheduledDestinations:ds}});
   assert.equal(next.intentId,r.intentId);
   try{assert.equal((await dispatchV76PinterestVideo(makeInput(next,1),deps)).outcome,'published');}finally{currentRevision=revision;}
 });
 await safe('real partial retry receipt dispatches only the failed sibling',async()=>{
   const r=makeReceipt('r2-narrowed',ds);
   await dispatchV76PinterestVideo(makeInput(r),deps);
   await dispatchV76PinterestVideo(makeInput(r,1),{...deps,publishVideo:async()=>({outcome:'failed',evidence:{stage:'registered',classification:'failed',error:'rejected'}})});
   const child:any={...r,intentId:r.intentId+'child',priorIntentId:r.intentId,onlyPending:true,dispatchDestinationIds:[r.destinations[1].id],confirmedAt:new Date().toISOString()};
   child.fingerprint=publishConfirmationFingerprint(child);
   const validated=validateImmediatePublishReceipt(child,{draftId:child.draftId,title:child.title,description:child.description,altText:child.altText,destinationUrl:child.destinationUrl,imageUrls:child.media.map((m:any)=>m.url)},child.dispatchDestinationIds);
   assert.equal(validated.ok,true);
   assert.equal((await dispatchV76PinterestVideo(makeInput(child,1),deps)).outcome,'published');
 });
 await safe('nonempty media alt text generated by real builder has a valid fingerprint',async()=>{
   const withAlt=media.map(m=>({...m,altText:'  A green bowl on a table  ',posterUrl:'  https://cdn.test/poster.jpg  '}));
   const r=buildDueVideoReceipt({draftId:'r2-alt',updatedAt:revision,scheduledAt:new Date().toISOString(),payload:{contentId:'r2-alt',title:'Video',media:withAlt,imageUrl:media[0].url,scheduledDestinations:ds.slice(0,1)}});
   assert.equal(r.fingerprint,publishConfirmationFingerprint(r),'builder and validator must use the same per-media alt identity');
   assert.equal(r.media[0].altText,'A green bowl on a table');assert.equal(r.media[0].posterUrl,'https://cdn.test/poster.jpg');
   const validated=validateImmediatePublishReceipt(r,{draftId:r.draftId,title:r.title,description:r.description,altText:r.altText,destinationUrl:r.destinationUrl,imageUrls:r.media.map(m=>m.url)},r.dispatchDestinationIds);
   assert.equal(validated.ok,true);
 });
 await safe('ready crash recovery uses frozen private bytes when original upload is gone',async()=>{
   const i=makeInput(makeReceipt('r2-ready-frozen'));
   await assert.rejects(dispatchV76PinterestVideo(i,{...deps,claimReady:async()=>{throw new Error('simulated crash');}}),/simulated crash/);
   await assert.rejects(loadReadyPrivateVideoSources(recoveryDb,i,{...materializer,download:async()=>{throw new Error('frozen object missing');}}),/frozen object missing/);
   await assert.rejects(loadReadyPrivateVideoSources(recoveryDb,i,{...materializer,download:async()=>new Blob(['corrupt'],{type:'video/mp4'})}),/publish_ready_asset_bytes_conflict/);
   const asset=await db.query('select asset.id,asset.object_path from publish_assets asset join publish_intents intent on intent.id=asset.publish_intent_id where intent.intent_id=$1',[i.receipt.intentId]);
   const frozen=asset.rows[0] as {id:string;object_path:string};
   await db.query('update publish_assets set object_path=$2 where id=$1',[frozen.id,'22222222-2222-4222-8222-222222222222/publish/wrong-owner.mp4']);
   await assert.rejects(deps.loadReadySources(i),/publish_ready_asset_graph_invalid/);
   await db.query('update publish_assets set object_path=$2 where id=$1',[frozen.id,frozen.object_path]);
   const frozenOnly={...materializer,download:async(_bucket:any,path:string)=>{if(path.includes('/uploads/'))throw new Error('source object removed');return file;}};
   assert.equal((await dispatchV76PinterestVideo(i,{...deps,materializeSources:(input:any,lease:any)=>materializePrivateVideoSources(input,lease,frozenOnly),loadReadySources:(input:any)=>loadReadyPrivateVideoSources(recoveryDb,input,frozenOnly)})).outcome,'published');
 });
 await db.close();
 console.log('Independent expected-safe adversarial failures:',failures);
 if(failures)process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1;});
`;
const compiled = ts.transpileModule(prefix + checks, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, esModuleInterop: true } }).outputText;
const harness = new (Module as any)(probePath, module);
harness.filename = probePath;
harness.paths = (Module as any)._nodeModulePaths(resolve(probePath, ".."));
harness._compile(compiled, probePath);
