#!/usr/bin/env python
"""probe_v82_task4b.py — test-DB E2E for the VIDEO child-intent retry (task 4b).

The mock suite proves the ordering and the receipt shape, but it stubs the RPC:
it cannot say whether `publish_intent_confirm_prepare_v82` actually accepts the
receipt our production builder produces, binds the lineage, inherits the attempt
or refuses a second redemption. Those are SQL facts and only a database can
answer them.

The receipts are NOT written here. They are generated by the production
TypeScript builders (`scripts/emit-v82-child-receipt.ts`) and read from JSON,
because the receipt carries a fingerprint that must equal the SHA-256 of its own
canonical serialization — hand-written JSON cannot satisfy that, and a Python
reimplementation would be a second copy to keep in sync.

TEST DATABASE ONLY. The target ref is asserted against production before any
statement is sent; a mismatch aborts before the first network call.

★ STATUS: INCOMPLETE — BLOCKED ON FIXTURE CONSTRUCTION, NOT ON THE FEATURE.
   E5/E6/E7 pass (the refusal paths, which need no parent fixture). E1-E4 are
   unverified because this probe cannot build the PARENT fixture: parking a
   destination at `delivery_unknown` requires walking
   prepared -> materialized -> claimed -> attempt(unknown), and
   `v76_legacy_transition_guard` refuses the `claimed` step with
   `materialization_required` (migrate_v76:634-670) until a full
   publish_assets / publish_asset_deliveries / publish_asset_delivery_items
   graph exists for the intent.

   The guard is CORRECT and must not be worked around. In particular the
   `v76_frozen_legacy` escape hatch (migrate_v76:629) is NOT available: its
   meaning is "pre-v76 historical row, exempt from the transition guard", and
   setting it on a row we just created would be falsifying lineage to dodge the
   very protection under test.

   What is still needed: build the materialization graph the way production
   does — `publish_asset_lease_materialization` +
   `publish_asset_settle_video_item_v79` + `publish_asset_claim_ready_v78` —
   which also needs storage objects for the video. That is a larger fixture
   than this probe currently carries.
"""
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT.parent / "web"
PROD_REF = "jaxteelkecvlozdrdoog"
TEST_REF = "snulmwprsahzqvdbyenc"


def load_env(path, keys):
    out = {}
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8-sig", errors="replace").splitlines():
        t = line.strip()
        if not t or t.startswith("#") or "=" not in t:
            continue
        k, _, v = t.partition("=")
        k, v = k.strip(), v.strip().strip('"').strip("'")
        if k in keys and v:
            out[k] = v
    return out


TOKEN = load_env(ROOT / ".env.migration", ["SUPABASE_MIGRATION_TOKEN"]).get(
    "SUPABASE_MIGRATION_TOKEN", "")
if not TOKEN:
    sys.exit("SUPABASE_MIGRATION_TOKEN missing")

print("=" * 70)
print(f"TARGET project_ref : {TEST_REF}")
print(f"PRODUCTION ref     : {PROD_REF}")
assert TEST_REF != PROD_REF, "ABORT: target is production"
print("ASSERTION OK: target != production. Proceeding.")
print("=" * 70)


def q(sql):
    url = f"https://api.supabase.com/v1/projects/{TEST_REF}/database/query"
    req = urllib.request.Request(
        url,
        data=json.dumps({"query": sql}).encode("utf-8"),
        headers={"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=180) as r:
            return r.status, json.loads(r.read().decode("utf-8") or "[]")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode("utf-8")


passed = failed = 0


def check(name, ok, detail=""):
    global passed, failed
    if ok:
        passed += 1
        print(f"  PASS  {name}" + (f"\n        {detail}" if detail else ""))
    else:
        failed += 1
        print(f"  FAIL  {name}\n        {detail}")


def lit(s):
    """Single-quoted SQL literal."""
    return "'" + str(s).replace("'", "''") + "'"


# ── Fixed identities for this probe ─────────────────────────────────────────
USER = "00000000-0000-4000-8000-0000000004b1"
CHECK_ID = str(uuid.UUID(int=0x4B1C0000000000000000000000000001))
# v76 validates the destination against a CONNECTED social_connections row
# (migrate_v76:839-849), and requires a v4-shaped uuid, so the connection is a
# real fixture created below rather than a readable placeholder.
CONN_ID = "4b1c0000-0000-4000-8000-000000000001"
OUT = ROOT.parent / ".e2e-tmp" / "receipts_e2e.json"
OUT.parent.mkdir(parents=True, exist_ok=True)

# ── Clean slate (before the fixture, so the fixture survives) ──────────────
CLEAN = f"""
delete from public.publish_reconcile_checks where owner_user_id = {lit(USER)};
delete from public.publish_intent_destinations where publish_intent_id in (
  select id from public.publish_intents where user_id = {lit(USER)});
delete from public.publish_intents where user_id = {lit(USER)};
"""
q(CLEAN)

# ── The connected-account fixture the receipt validation demands ────────────
s, b = q(f"""
insert into public.social_connections(
  id, user_id, vibepin_user_id, provider, platform, connection_status,
  scopes, needs_reconnect, token_version, disconnected_at)
values ({lit(CONN_ID)}::uuid, {lit(USER)}::uuid, {lit(USER)}::uuid,
        'pinterest', 'pinterest', 'connected', '{{}}', false, 1, null)
on conflict (id) do update set
  connection_status = 'connected', disconnected_at = null,
  user_id = excluded.user_id, provider = 'pinterest'
returning id, connection_status;
""")
check("fixture: a connected Pinterest account exists for the probe user",
      s == 201 and b and b[0]["connection_status"] == "connected", f"{s} {str(b)[:300]}")

# ── Generate the receipts with the PRODUCTION builders ──────────────────────
print("\nGenerating receipts with the production TypeScript builders...")
proc = subprocess.run(
    ["npx", "tsx", "scripts/emit-v82-child-receipt.ts", str(OUT), USER, CHECK_ID, CONN_ID],
    cwd=str(WEB), capture_output=True, text=True, shell=(os.name == "nt"),
)
if proc.returncode != 0:
    sys.exit(f"receipt generation failed:\n{proc.stdout}\n{proc.stderr}")
print(proc.stdout.strip())

R = json.loads(OUT.read_text(encoding="utf-8"))
parent, child = R["parent"], R["child"]
DEST = R["destinationId"]
DRAFT, CONTENT = R["draftId"], R["contentId"]

check("receipt lineage: child.priorIntentId == parent.intentId",
      child["priorIntentId"] == parent["intentId"],
      f"{child['priorIntentId']} vs {parent['intentId']}")
check("receipt shape: onlyPending true and dispatch set is exactly the destination",
      child["onlyPending"] is True and child["dispatchDestinationIds"] == [DEST],
      json.dumps(child["dispatchDestinationIds"]))

# ── Build the PARENT intent, then put its destination at delivery_unknown ───
# The parent is created through v76's own prepare so the materialization graph
# is the real one; only the terminal status is set directly, because reaching
# `delivery_unknown` organically would require a provider that never answers.
s, b = q(f"""
select public.publish_intent_confirm_prepare(
  {lit(USER)}::uuid, {lit(json.dumps(parent))}::jsonb) as r;
""")
check("parent intent created by v76 prepare", s == 201, f"{s} {str(b)[:400]}")

# The status is NOT forced. `v76_legacy_transition_guard` requires the row to
# arrive at `delivery_unknown` from `claimed`, with a matching
# `provider_publish_attempts` row at `unknown` (migrate_v76:674-691) — a real
# state machine, and forcing the column would be testing a state production can
# never produce. So the probe walks it: claim, start an attempt, settle it
# `unknown`, which is exactly what a provider call that never answered does.
s, b = q(f"""
do $v82_park$
declare
  v_intent public.publish_intents%rowtype;
  v_claim uuid := gen_random_uuid();
  v_attempt_id uuid;
begin
  select * into v_intent from public.publish_intents
   where user_id = {lit(USER)}::uuid and intent_id = {lit(parent['intentId'])};

  update public.publish_intent_destinations
     set status = 'claimed', claim_token = v_claim, claimed_at = now(), updated_at = now()
   where publish_intent_id = v_intent.id and destination_id = {lit(DEST)};

  select (public.publish_provider_attempt_start(
    {lit(USER)}::uuid, {lit(parent['intentId'])}, {lit(DEST)}, v_claim, 1
  ) ->> 'attemptId')::uuid into v_attempt_id;

  perform public.publish_provider_attempt_settle(
    {lit(USER)}::uuid, v_attempt_id, v_claim, 'unknown', null, null, null,
    jsonb_build_object('reason','unknown_outcome'));
end $v82_park$;
""")
check("parent destination reaches delivery_unknown through the REAL state machine",
      s == 201, f"{s} {str(b)[:400]}")

s, b = q(f"""
select d.status, d.attempt from public.publish_intent_destinations d
  join public.publish_intents i on i.id = d.publish_intent_id
 where i.user_id = {lit(USER)}::uuid and i.intent_id = {lit(parent['intentId'])}
   and d.destination_id = {lit(DEST)};
""")
check("parent destination is parked at delivery_unknown",
      s == 201 and b and b[0]["status"] == "delivery_unknown", f"{s} {b}")

# ── The confirmed_absent proof, bound to the parent intent's DB id ──────────
# This is what the must-do fix now records from the application. Binding it to
# the parent row id is the thing the RPC checks at migrate_v82:458.
s, b = q(f"""
insert into public.publish_reconcile_checks(
  id, owner_user_id, draft_id, scheduled_at, provider, social_connection_id,
  attempt, publish_intent_id, destination_id, outcome)
select {lit(CHECK_ID)}::uuid, {lit(USER)}::uuid, {lit(DRAFT)}, {lit(R['scheduledAt'])}::timestamptz,
       'pinterest', {lit(R['connectionId'])}, 1, i.id, {lit(DEST)}, 'confirmed_absent'
  from public.publish_intents i
 where i.user_id = {lit(USER)}::uuid and i.intent_id = {lit(parent['intentId'])}
returning id, publish_intent_id is not null as bound;
""")
check("confirmed_absent proof recorded and bound to the parent intent row",
      s == 201 and b and b[0]["bound"] is True, f"{s} {b}")

# ── E1: REDEEM — the real call the route makes ──────────────────────────────
s, b = q(f"""
select public.publish_intent_confirm_prepare_v82(
  {lit(USER)}::uuid, {lit(json.dumps(child))}::jsonb,
  {lit(R['childSourceFingerprint'])}, {lit(CHECK_ID)}::uuid) as r;
""")
check("E1 redemption ACCEPTED: the production receipt opens a child intent",
      s == 201, f"{s} {str(b)[:500]}")

# ── E2: lineage is bound in the database, not merely requested ──────────────
s, b = q(f"""
select c.intent_id as child_intent,
       (c.prior_intent_id = p.id) as prior_bound,
       c.source_identity_fingerprint = {lit(R['childSourceFingerprint'])} as fp_bound
  from public.publish_intents c
  join public.publish_intents p
    on p.user_id = c.user_id and p.intent_id = {lit(parent['intentId'])}
 where c.user_id = {lit(USER)}::uuid and c.intent_id = {lit(child['intentId'])};
""")
check("E2 child.prior_intent_id points at the parent row, fingerprint stored",
      s == 201 and b and b[0]["prior_bound"] is True and b[0]["fp_bound"] is True,
      f"{s} {b}")

# ── E3: destination lineage + attempt inheritance (parent + 1) ──────────────
s, b = q(f"""
select cd.attempt as child_attempt, pd.attempt as parent_attempt,
       (cd.retry_of_destination_id = pd.id) as retry_bound
  from public.publish_intents c
  join public.publish_intent_destinations cd on cd.publish_intent_id = c.id
  join public.publish_intents p on p.user_id = c.user_id
   and p.intent_id = {lit(parent['intentId'])}
  join public.publish_intent_destinations pd on pd.publish_intent_id = p.id
   and pd.destination_id = cd.destination_id
 where c.user_id = {lit(USER)}::uuid and c.intent_id = {lit(child['intentId'])}
   and cd.destination_id = {lit(DEST)};
""")
ok = (s == 201 and b and b[0]["retry_bound"] is True
      and b[0]["child_attempt"] == b[0]["parent_attempt"] + 1)
check("E3 child destination binds retry_of_destination_id and inherits attempt+1",
      ok, f"{s} {b}")

# ── E4: the SAME receipt replays into the SAME child (crash-replay safe) ────
# The child intent id is deterministic per proof, so a crash between prepare and
# dispatch re-sends the identical receipt. That must succeed, not be refused —
# otherwise the destination is stranded forever.
s, b = q(f"""
select public.publish_intent_confirm_prepare_v82(
  {lit(USER)}::uuid, {lit(json.dumps(child))}::jsonb,
  {lit(R['childSourceFingerprint'])}, {lit(CHECK_ID)}::uuid) as r;
""")
check("E4 replaying the identical receipt is ACCEPTED (same child, not a second)",
      s == 201, f"{s} {str(b)[:400]}")

s, b = q(f"""
select count(*) as n from public.publish_intents
 where user_id = {lit(USER)}::uuid and prior_intent_id is not null;
""")
check("E4b and only ONE child exists after the replay",
      s == 201 and b and b[0]["n"] == 1, f"{s} {b}")

# ── E5: a SECOND, different redemption of the same proof is refused ─────────
# One confirmed_absent authorizes one retry. A different child receipt against
# the same proof is the "spend the coupon twice" case.
s, b = q(f"""
do $$
declare v_err text; v_receipt jsonb;
begin
  v_receipt := {lit(json.dumps(child))}::jsonb;
  -- a DIFFERENT child intent id, everything else identical
  v_receipt := jsonb_set(v_receipt, '{{intentId}}',
    to_jsonb({lit(child['intentId'] + 'X')}::text));
  begin
    perform public.publish_intent_confirm_prepare_v82(
      {lit(USER)}::uuid, v_receipt, {lit(R['childSourceFingerprint'])},
      {lit(CHECK_ID)}::uuid);
    raise exception 'NO_ERROR_RAISED';
  exception when others then v_err := sqlerrm;
  end;
  if v_err <> 'retry_not_allowed' then
    raise exception 'unexpected: %', v_err;
  end if;
end $$;
""")
check("E5 a second, different redemption of the same proof ⇒ retry_not_allowed",
      s == 201, f"{s} {str(b)[:400]}")

# ── E6: without the proof, the same receipt is refused by v78 semantics ─────
# The control. It proves the child opened in E1 because of the PROOF, not
# because the receipt happened to be acceptable on its own.
s, b = q(f"""
do $$
declare v_err text;
begin
  begin
    perform public.publish_intent_confirm_prepare_v82(
      {lit(USER)}::uuid, {lit(json.dumps(child))}::jsonb,
      {lit(R['childSourceFingerprint'])}, null);
    raise exception 'NO_ERROR_RAISED';
  exception when others then v_err := sqlerrm;
  end;
  if v_err = 'NO_ERROR_RAISED' then
    raise exception 'v78 delegation accepted a delivery_unknown parent';
  end if;
end $$;
""")
check("E6 CONTROL: same receipt with NO proof is refused (v78 delegation)",
      s == 201, f"{s} {str(b)[:400]}")

# ── E7: the proof only vouches for its own destination ──────────────────────
s, b = q(f"""
do $$
declare v_err text; v_receipt jsonb;
begin
  v_receipt := {lit(json.dumps(child))}::jsonb;
  v_receipt := jsonb_set(v_receipt, '{{dispatchDestinationIds}}',
    '["pinterest:conn-SOMEONE-ELSE"]'::jsonb);
  begin
    perform public.publish_intent_confirm_prepare_v82(
      {lit(USER)}::uuid, v_receipt, {lit(R['childSourceFingerprint'])},
      {lit(CHECK_ID)}::uuid);
    raise exception 'NO_ERROR_RAISED';
  exception when others then v_err := sqlerrm;
  end;
  if v_err <> 'retry_not_allowed' then
    raise exception 'unexpected: %', v_err;
  end if;
end $$;
""")
check("E7 a dispatch set other than the proof's destination ⇒ retry_not_allowed",
      s == 201, f"{s} {str(b)[:400]}")

# ── Clean up, fixture included ──────────────────────────────────────────────
q(CLEAN + f"delete from public.social_connections where id = {lit(CONN_ID)}::uuid;")

print("\n" + "=" * 70)
print(f"{passed} passed, {failed} failed")
print("=" * 70)
sys.exit(1 if failed else 0)
