import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, baseURL: "http://127.0.0.1:3000" });
page.on('console', msg => console.log('console', msg.type(), msg.text()));
page.on('pageerror', err => console.log('pageerror', err.message));
await page.goto("/app/studio", { waitUntil: "networkidle", timeout: 45000 });
await page.getByTestId("composer-panel").waitFor();
await page.getByTestId("add-product-images").click({ force: true });
await page.waitForTimeout(3000);
console.log('picker count', await page.getByTestId('product-picker').count());
await browser.close();
